### ISSUE TITLE
菜单第一次点击，整体网页会抖一下

### ISSUE THREAD

**Issue by aohanhongzhi** [Xi-Yuer/GO-CMS#4]
![image](https://github.com/Xi-Yuer/GO-CMS/assets/37319319/92aabf66-e58e-406c-b43c-f030e6bd5567)

**Comment by Xi-Yuer** [comment]
好的，主要是每个页面做了懒加载，该懒加载组件会让页面重新渲染，所以看起来会抖一下

**Comment by aohanhongzhi** [comment]
> 好的，主要是每个页面做了懒加载，该懒加载组件会让页面重新渲染，所以看起来会抖一下

意思是，整个前端app不是一起加载的，是分步懒加载的? 思路很好，那我建议先把整体框架加载出来，菜单加载出来。不至于整体刷新啊，抖一下感觉很不常见。

**Comment by Xi-Yuer** [comment]
好的，谢谢你的建议，我会尽快修改
