### ISSUE TITLE
有点感觉层次感太多了

### ISSUE THREAD

**Issue by aohanhongzhi** [Xi-Yuer/GO-CMS#5]
<img width="1515" alt="image" src="https://github.com/Xi-Yuer/GO-CMS/assets/37319319/b6e5d57b-d7ff-4390-9123-07827c0305bb">

**Comment by Xi-Yuer** [comment]
主要是为了营造一种卡片式风格的效果

**Comment by aohanhongzhi** [comment]
可能还可以优化下

**Comment by Xi-Yuer** [comment]
![image](https://github.com/Xi-Yuer/GO-CMS/assets/81563877/3655482c-4316-4d10-b5b7-9f7ec6a18931)
